mode = "local"
max_retries = 10

[cloud]
api_key = "apf_vjmm7797fwnnfop82479hh8y"
api_url = "https://apifreellm.com/api/v1/chat"
smart_model_id = "gpt-4o"
dumb_model_id = "gpt-3.5-turbo"
protocol = "custom"

[local]
api_url = "http://localhost:11434/api/generate"
smart_model_id = "qwen2.5:3b-instruct"
dumb_model_id = "tinyllama"
